/*
 * This source file was generated by the Gradle 'init' task
 */
package lab7;
import java.util.*;
import heap.Heap;
import avl.AVL;
import java.util.Map.Entry;


public class Huffman {
    
    public String getGreeting() {
        return "Hello World!";
    }
    public 

    public static void main(String[] args) {
        System.out.println(new Huffman().getGreeting());
    }

    public static String decode(Node root, String input){
	String code = "";
	Node current = root;
	int len = input.length();

	for(int i = 0; i < len; i++){
	    if (input.charAt(i) == '0') {
		current = current.left;
	    } else {
		current = current.right;
	    }
	    if (current.left == null && current.right == null){
		code += current.data;
		current = root;
	    }
	}
	return code;
    }

    public static String encode(String input, PriorityQueue<> eTable){
	
    }
	
    
}
