/*
 * This source file was generated by the Gradle 'init' task
 */
package lab7;
import java.util.HashMap

public class Huffman {
    
    public String getGreeting() {
        return "Hello World!";
    }
    public 


	hello aldo



	hello aldo




	hello aldo



	goodbye aldo

    public static void main(String[] args) {
        System.out.println(new Huffman().getGreeting());
    }
}
